# Bug Hunt Pipeline
# Systematic bug discovery, elegant triage, refinement, and implementation

name: bug-hunt
description: Discover bugs with fresh eyes, triage elegantly, refine tasks, implement fixes

stages:
  # Stage 1: Explore codebase and document bugs (8 iterations)
  - name: discover
    stage: bug-discovery
    runs: 8

  # Stage 2: Triage bugs, find patterns, create elegant solutions as beads
  - name: triage
    stage: bug-triage
    runs: 2
    inputs:
      from: discover
      select: latest

  # Stage 3: Refine the tasks created during triage
  - name: refine
    stage: refine-tasks
    runs: 3
    inputs:
      from: triage
      select: latest

  # Stage 4: Implement the fixes
  - name: fix
    stage: ralph
    runs: 25
    inputs:
      from: refine
      select: latest
