# Refine Pipeline
# Improves plan, then refines tasks

name: refine
description: Complete planning refinement - plan first, then tasks

stages:
  - name: improve-plan
    stage: improve-plan
    runs: 5

  - name: refine-tasks
    stage: refine-tasks
    runs: 5
    inputs:
      from: improve-plan
      select: latest
